### ISSUE TITLE
401 error trying to reload a tab after inactivity

### ISSUE THREAD

**Issue by apawlik** [stencila/cloud#10]
After about 30 min inactivity on the Hub, when reloading the tab with an open project I get the following error:

`ERROR:An error occurred with request "GET http://cloud-test.stenci.la/v1/sessions!/stencila-cloud-233563f82b21ab0bc2200243/manifest"`

Developer console:

![image](https://user-images.githubusercontent.com/2358535/42143684-8e8404a8-7e0a-11e8-9db8-d9c3a56a56ee.png)

**Comment by nokome** [comment]
Closing as stale.
